// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:033f20c2-3202-49d1-bba8-7ae37900bd73",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Hu23irziF",
    "aws_user_pools_web_client_id": "230jmgbpnj7k2kup6gtucsf22m",
    "oauth": {},
    "aws_user_files_s3_bucket": "cypressxstoragexbucket1223299848iods-dev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_bots": "enable",
    "aws_bots_config": [
        {
            "name": "ScheduleAppointment_dev",
            "alias": "$LATEST",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;